dist: xenial

addons:
  snaps:
  - name: dotnet-sdk
    confinement: classic 
    channel: latest/beta
    
sudo: required

language: csharp
mono: none

solution: GenHTTP.sln

script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet build GenHTTP.sln -c Release
  - dotnet test -c Release -parallel none --no-build GenHTTP.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ParallelizeTestCollections=false /p:Exclude=\"[xunit.*]*,[*Test*]*\" 
  - bash <(curl -s https://codecov.io/bash)
